"""Render the catalog as a standalone HTML page.

The page carries the catalog and the downloadable files inside it, so it works
from disk with no server, no network and no build step. The markup and styling
live in ``templates/page.html``; this module injects the data and wraps the
result in a document skeleton.
"""

import json
from dataclasses import asdict
from importlib import resources
from pathlib import Path

from earlywarn import paths
from earlywarn.catalog import CATALOG, IDEA_SUMMARIES, IDEAS
from earlywarn.export import as_rows
from earlywarn.models import COLUMN_NAMES

BODY_MARKER = "<!--BODY-->"
DATA_MARKER = "/*__DATA__*/"

DOWNLOAD_NOTE = (
    "Download saves the file straight from this page - no request goes anywhere. "
    "If a preview host blocks the save, Copy puts the same text on your clipboard."
)

FOOTER_NOTE = (
    "Generated by 'earlywarn page'. Licenses and URLs are recorded as published by "
    "each provider - confirm them on the landing page the first time you download. "
    "No datasets are embedded here; run 'earlywarn fetch' to populate data/raw/."
)

DOCUMENT = (
    "<!doctype html>\n<html lang=\"en\">\n<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "{head}\n</head>\n<body>\n{body}\n</body>\n</html>\n"
)

FILE_DESCRIPTIONS = {
    paths.CATALOG_CSV: "The full catalog, one row per dataset.",
    paths.CATALOG_JSON: "The same catalog as JSON records.",
    paths.REFERENCE_CSV: "WHO estimate against official Bangladesh road deaths, 2021.",
    paths.REFERENCE_JSON: "The same reference figures as JSON records.",
}


def read_template() -> str:
    """Read the page template shipped with the package.

    Returns:
        str: Template source.
    """
    return resources.files("earlywarn.templates").joinpath("page.html").read_text(
        encoding="utf-8"
    )


def count_rows(text: str, is_json: bool) -> int:
    """Count the records in a serialised file.

    Args:
        text: File contents.
        is_json: Whether the contents are JSON.

    Returns:
        int: Number of records.
    """
    if is_json:
        return len(json.loads(text))
    return max(0, len([line for line in text.splitlines() if line.strip()]) - 1)


def collect_files(root: Path) -> list[dict]:
    """Read the generated files so the page can serve them for download.

    Args:
        root: Data directory to read from.

    Returns:
        list[dict]: One entry per file that exists, in display order.
    """
    files = []
    for relative, description in FILE_DESCRIPTIONS.items():
        path = root / relative
        if not path.exists():
            continue
        # Decode the bytes rather than read_text so CRLF line endings survive
        # and the download is byte-identical to the file on disk.
        content = path.read_bytes().decode("utf-8")
        is_json = path.suffix == ".json"
        files.append({
            "name": path.name,
            "description": description,
            "content": content,
            "mime": "application/json" if is_json else "text/csv",
            "rows": count_rows(content, is_json),
        })
    return files


def build_payload(root: Path) -> dict:
    """Assemble everything the page needs to render itself.

    Args:
        root: Data directory holding the generated files.

    Returns:
        dict: The payload embedded in the page.
    """
    reference_path = root / paths.REFERENCE_JSON
    reference = (
        json.loads(reference_path.read_text(encoding="utf-8"))
        if reference_path.exists()
        else []
    )
    return {
        "columns": COLUMN_NAMES,
        "catalog": as_rows(),
        "ideas": [
            {"id": key, "label": label, "note": IDEA_SUMMARIES.get(key, "")}
            for key, label in IDEAS.items()
        ],
        "reference": reference,
        "files": collect_files(root),
        "download_note": DOWNLOAD_NOTE,
        "footer_note": FOOTER_NOTE,
    }


def render(root: Path) -> tuple[str, str]:
    """Render the page's head and body.

    Args:
        root: Data directory holding the generated files.

    Returns:
        tuple[str, str]: The head fragment and the body fragment.

    Raises:
        ValueError: If the template is missing a marker.
    """
    template = read_template()
    for marker in (BODY_MARKER, DATA_MARKER):
        if marker not in template:
            raise ValueError(f"page template is missing its {marker} marker")

    payload = json.dumps(build_payload(root), ensure_ascii=False).replace("</", "<\\/")
    template = template.replace(DATA_MARKER, f"var DATA = {payload};")
    head, body = template.split(BODY_MARKER, 1)
    return head.strip(), body.strip()


def build_page(
    data_dir: Path | str | None = None,
    fragment_path: Path | None = None,
) -> Path:
    """Write the catalog page.

    Args:
        data_dir: Data directory, or None for the default. The page is written
            to ``index.html`` inside it.
        fragment_path: Optional path for a copy without the document skeleton,
            for hosts that supply their own.

    Returns:
        Path: Path of the standalone page.
    """
    root = paths.resolve(data_dir)
    head, body = render(root)

    page_path = root / paths.PAGE_HTML
    page_path.parent.mkdir(parents=True, exist_ok=True)
    page_path.write_text(DOCUMENT.format(head=head, body=body), encoding="utf-8")

    if fragment_path is not None:
        fragment_path.parent.mkdir(parents=True, exist_ok=True)
        fragment_path.write_text(f"{head}\n{body}\n", encoding="utf-8")

    return page_path
